### ISSUE TITLE
Oneway incorrect

### ISSUE THREAD

**Issue by xivk** [openplannerteam/routable-tiles-ontology#8]
The oneway tag is translated incorrectly:

https://github.com/openplannerteam/routable-tiles-ontology/blob/master/mapping_config.json#L175

oneway=yes = in order.

**Comment by hdelva** [comment]
Good eye, should be fixed now!

**Comment by xivk** [comment]
Wow, awesome, will try updating again... :+1: We need some routing unittests, we have some with ANYWAYS, wouldn't be a bad idea to have them run over the tiles.
